// <auto-generated />
namespace Cape_Senior_Center_Inventory_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class uom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uom));
        
        string IMigrationMetadata.Id
        {
            get { return "201811071500268_uom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
